# Generated by Django 3.1.5 on 2021-12-15 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=200)),
                ('Image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
