# Generated by Django 3.1.5 on 2021-12-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Designtion', models.CharField(max_length=100)),
                ('Photo', models.ImageField(upload_to='pics')),
                ('Review', models.TextField()),
            ],
        ),
    ]
