# Generated by Django 3.1.5 on 2021-12-15 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_testimonials'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimonials',
            new_name='Testimonial',
        ),
    ]
