# Generated by Django 3.1.5 on 2021-12-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20211215_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='Designtion',
            new_name='Designation',
        ),
    ]
