# Generated by Django 3.1.5 on 2021-12-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='Facebook',
            field=models.CharField(blank=100, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='Instagram',
            field=models.CharField(blank=100, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='LinkedIn',
            field=models.CharField(blank=100, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='Twitter',
            field=models.CharField(blank=100, max_length=100, null=True),
        ),
    ]
