# Generated by Django 3.1.5 on 2021-12-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('Image', models.ImageField(upload_to='pics')),
                ('Content', models.TextField()),
                ('Tag_1', models.CharField(blank=True, max_length=50, null=True)),
                ('Tag_2', models.CharField(blank=True, max_length=50, null=True)),
                ('Tag_3', models.CharField(blank=True, max_length=50, null=True)),
                ('Tag_4', models.CharField(blank=True, max_length=50, null=True)),
                ('Tag_5', models.CharField(blank=True, max_length=50, null=True)),
                ('Tag_6', models.CharField(blank=True, max_length=50, null=True)),
                ('Tag_7', models.CharField(blank=True, max_length=50, null=True)),
                ('Tag_8', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
