# Generated by Django 3.1.5 on 2021-12-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
