# Generated by Django 3.1.5 on 2021-12-18 09:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
