# Generated by Django 3.1.5 on 2021-12-18 10:04

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_auto_20211218_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Content',
            field=froala_editor.fields.FroalaField(default=''),
            preserve_default=False,
        ),
    ]
