# Generated by Django 3.1.5 on 2021-12-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_auto_20211224_0534'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('home_title', models.CharField(max_length=100)),
                ('home_heading', models.CharField(max_length=25)),
                ('home_heading_1', models.CharField(max_length=25)),
                ('home_heading_2', models.CharField(max_length=25)),
                ('home_heading_3', models.CharField(max_length=25)),
                ('home_description', models.CharField(max_length=250)),
                ('who_are_we_icon_heading', models.CharField(max_length=100)),
                ('who_are_we_heading_1', models.CharField(max_length=100)),
                ('who_are_we_heading_2', models.CharField(max_length=100)),
                ('who_are_we_text', models.TextField()),
                ('who_are_we_check_1', models.CharField(max_length=50)),
                ('who_are_we_check_2', models.CharField(max_length=50)),
                ('service_icon_heading', models.CharField(max_length=100)),
                ('service_heading_1', models.CharField(max_length=50)),
                ('service_heading_2', models.CharField(max_length=50)),
                ('service_text', models.TextField()),
                ('team_heading_1', models.CharField(max_length=100)),
                ('team_heading_2', models.CharField(max_length=100)),
                ('team_text', models.TextField()),
                ('testimonial_heading_1', models.CharField(max_length=100)),
                ('testimonial_heading_2', models.CharField(max_length=100)),
                ('testimonial_text', models.TextField()),
                ('blog_text', models.TextField()),
                ('contact_heading', models.CharField(max_length=100)),
                ('contact_desc', models.CharField(max_length=250)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.CharField(max_length=50)),
                ('contact_address', models.CharField(max_length=100)),
                ('linked_by_name', models.CharField(max_length=16)),
            ],
        ),
    ]
